### ISSUE TITLE
Specialized Input Settings regenerate a warning

### ISSUE THREAD

**Issue by sergeifilippov** [panoply/Liquify#24]
Given the following in my `settings_schema.json`;

```json
      ...
      {
        "type": "font_picker",
        "id": "headings_font",
        "label": "t:sections.split-extra-words.settings_schema.typography.settings.font_family",
        "default": "dm_sans_n5"
      },
      {
        "type": "range",
        "id": "headings_size",
        "label": "t:sections.split-extra-words.settings_schema.typography.settings.base_size",
        "min": 24,
        "max": 100,
        "step": 1,
        "unit": "px",
        "default": 90
      },
      ...
```

I get the following warning in VSCode,

`Value is not accepted. Valid values: "header", "paragraph", "text", "textarea".`

I thought `font_picker` & `range` are valid input configuration according to [Shopify Dev Docs](https://shopify.dev/docs/themes/architecture/settings/input-settings#specialized-input-settings)?

Could you point me to the file I need to update to add the **Specialized Input Settings** and send you a PR. 🙏🏻

I struggle to find it in the repo 🙈

Amazing plugin!

**Comment by panoply** [comment]
Hey @sergeifilippov so the talented @muchisx has addressed this in https://github.com/panoply/liquify-schema/pull/2 which I will get around to merging hopefully tonight or tomorrow. Then I'll update the nightly [vsix](https://github.com/panoply/vscode-liquid/blob/next/shopify-liquid-4.0.0.vsix). 

---

### Plans for Liquify and upcoming releases

This repo is Liquify which will be v5 of vscode-liquid ~ so you are here in the future. The current extension which lives [here](https://github.com/panoply/vscode-liquid) but it will be superseded by this project. 

Current plans are as follows:

#### Release **v4.0.0** of vscode-liquid

Version 4.0 ships with almost all the features found here in Liquify, minus the linting/validations. 

#### Allow users to upgrade and patch any issues occuring in 4.0

Because version 4.0 has breaking changes, developers will need some time to upgrade. This will allow for devs to submit any issues and be ready for the next **major** version (which is Liquify - i.e: v5.0)

#### Version 4.0 > 5.0

There will be minor version bumps following v4.0 and once things are solid, the supersede will shipped and all users can begin to leverage Liquify and all its features, this will be available in a separate extension. Upgrading will essentially be a matter of installing Liquify. 

If you are interested, I am always open for contributions etc. This has been a huge project for me but we are almost there. I can notify you once I've shipped the nightly VSIX with this fix if you like. Are you already leveraging v4?

**Comment by sergeifilippov** [comment]
In that case, I'll just close this issue then 😄 

Can't wait for the next release.
